Assembler:
	@gcc -o asm_converter main.c asm2bin.c

Run:
	@./asm_converter fibonacci.asm 

Output:
	cat output.bin

help:
	@echo "Makefile"
	@echo "make Assmbler          -complie the main.c and asm2bin.c"
	@echo "make Run               -exe the file fibonacci.asm and make asm_converter"
	@echo "make output            -Print the output in termainl"

